### ISSUE TITLE
cl-platform-config is unable to determine platform for ARCH: x86_64

### ISSUE THREAD

**Issue by zioproto** [CumulusNetworks/cumulus-vx-vagrant#9]
steps to reproduce:

```sudo apt-get update```
```sudo apt-get upgrade```

The upgrade does not finish successfully because the ```cl-platform-config``` does not recognize the x86_64 ARCH
```
Setting up cl-platform-config (1.2-cl2.5+2) ...
ERROR:  Unable to determine platform for ARCH: x86_64
Error: Unable to find existing platform configuration directory: /usr/share/platform-config/UNKNOWN/UNKNOWN
dpkg: error processing cl-platform-config (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 cl-platform-config
E: Sub-process /usr/bin/dpkg returned an error code (1)
vagrant@cumulus:~$
```

**Comment by zioproto** [comment]
Oh I forgot to mention I am using the image CumulusVX-2.5.3-4eb681f3df86c478.box

**Comment by 8bitdad** [comment]
@zioproto Unfortunately you can not run apt-get upgrade on the VX image. From the documents.

In addition, you cannot upgrade the Cumulus VX operating system using apt-get upgrade|update or use ONIE. A new image is available with every Cumulus VX release. However, you can use apt-get to install additional software packages, whether they are Cumulus Linux-specific or Debian-specific.

**Comment by beddari** [comment]
IMO it would be better UX to actually have it run - then behaviour would be closer to a "real" system. Not directly related, but I don't really get why Cumulus Networks have chosen to "lock" VX down ...

**Comment by isharacomix** [comment]
I'm going to close this - VX 3.0 I believe fixes these problems as it is more consistent with the production release of Cumulus Linux.
